name: CI

on:
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_composer:
    name: Check composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict --no-check-lock

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
        min_stability: ['']
        name_suffix: ['']
        include:
          - php: '8.3'
            min_stability: 'dev'
            name_suffix: ' (dev deps)'

    name: PHP ${{ matrix.php }}${{ matrix.name_suffix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: xdebug

      - name: Configure stability
        if: "matrix.min_stability != ''"
        run: composer config minimum-stability "${{ matrix.min_stability }}"

      - name: Install Composer dependencies
        run: composer install --ansi --no-interaction --no-progress

      - name: Execute Unit Tests
        run: vendor/bin/phpunit
